### ISSUE TITLE
warnings when last task contained no JIRA ticket id

### ISSUE THREAD

**Issue by ghost** [pepl/App-TimeTracker-Jira#1]
$ whichpm App::TimeTracker::Command::Jira
/usr/local/share/perl/5.20.2/App/TimeTracker/Command/Jira.pm 0.4

$ tracker start --jira ABC-42
Worked 00:01:54 on project
Use of uninitialized value $id in sprintf at /usr/local/share/perl/5.20.2/App/TimeTracker/Command/Jira.pm line 201.
Use of uninitialized value $params[0] in sprintf at /usr/local/share/perl/5.20.2/App/TimeTracker/Utils.pm line 29.
Could not fetch JIRA ticket transitions: 
Use of uninitialized value $id in sprintf at /usr/local/share/perl/5.20.2/App/TimeTracker/Command/Jira.pm line 210.
Use of uninitialized value $params[0] in sprintf at /usr/local/share/perl/5.20.2/App/TimeTracker/Utils.pm line 29.
Could not fetch JIRA ticket: 
Last task did not contain a JIRA ticket id, not updating TimeWorked or Status.
Started working on project (JIRA:ABC-42) Create something at 09:57:42

**Comment by pepl** [comment]
Fixed in 0.5
